receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  postgresql:
    endpoint: api-database:5432
    transport: tcp
    username: ${env:POSTGRES_USER}
    password: ${env:POSTGRES_PASSWORD}
    databases:
      - ${POSTGRES_DB_NAME}
    collection_interval: 10s
    tls:
      insecure: true
    events:
      db.server.query_sample:
        enabled: true
      db.server.top_query:
        enabled: true

processors:
  memory_limiter:
    limit_mib: 1536
    spike_limit_mib: 512
    check_interval: 5s
  batch:
    timeout: 10s

  transform/datadogTransform:
    error_mode: ignore
    trace_statements:
      - context: resource
        statements:
          - set(resource.attributes["deployment.environment"], "${ENV}")

connectors:
  datadog/connector:

exporters:
  datadog:
    hostname: test-host
    api:
      site: datadoghq.com
      key: ${DD_API_KEY}
      fail_on_invalid_key: true
    tls:
      insecure_skip_verify: true
  debug:
    verbosity: detailed

service:
  pipelines:
    traces/datadogStage1:
      receivers: [otlp]
      processors: [transform/datadogTransform, memory_limiter, batch]
      exporters: [debug, datadog/connector]

    traces/datadogStage2:
      receivers: [datadog/connector]
      processors: [memory_limiter, batch]
      exporters: [datadog]

    metrics/datadogMetrics:
      receivers: [datadog/connector, postgresql]
      processors: [memory_limiter, batch]
      exporters: [datadog]
