receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  postgresql:
    endpoint: api-database:5432
    transport: tcp
    username: ${env:POSTGRES_USER}
    password: ${env:POSTGRES_PASSWORD}
    databases:
      - ${POSTGRES_DB_NAME}
    collection_interval: 10s
    tls:
      insecure: true
    events:
      db.server.query_sample:
        enabled: true
      db.server.top_query:
        enabled: true

processors:
  memory_limiter:
    limit_mib: 1536
    spike_limit_mib: 512
    check_interval: 5s
  batch:
    timeout: 10s

  transform/datadogTransform:
    error_mode: ignore
    trace_statements:
      - context: resource
        statements:
          - set(resource.attributes["deployment.environment"], "${ENV}")
          - set(resource.attributes["service.name"], "fallback-service-name") where resource.attributes["service.name"] == nil

exporters:
  otlp:
    endpoint: ${CLUSTER_OTEL_COLLECTOR_ENDPOINT}
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [transform/datadogTransform, memory_limiter, batch]
      exporters: [otlp]

    metrics:
      receivers: [otlp, postgresql]
      processors: [memory_limiter, batch]
      exporters: [otlp]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp]
