load_module modules/ngx_otel_module.so;

events {
    worker_connections 1024;
}

http {
    map $status $log_level {
        ~^1       "info";
        ~^2       "info";
        ~^3       "info";
        ~^4       "warn";
        ~^5       "error";
        default   "info";
    }

    log_format json_combined escape=json
    '{'
      '"time_local":"$time_local",'
      '"remote_addr":"$remote_addr",'
      '"request_method":"$request_method",'
      '"request_uri":"$request_uri",'
      '"status":$status,'
      '"body_bytes_sent":$body_bytes_sent,'
      '"request_time":$request_time,'
      '"upstream_response_time":"$upstream_response_time",'
      '"http_referer":"$http_referer",'
      '"http_user_agent":"$http_user_agent"',
      '"trace_id":"$otel_trace_id",'
      '"span_id":"$otel_span_id"'
    '}';

    access_log /dev/stdout json_combined;
    error_log stderr warn;

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    otel_service_name nginx-proxy;

    otel_exporter {
        endpoint otel-collector:4317;
    }

    server {
        listen 80;
        server_name localhost;
        otel_trace on;

        location / {
            otel_trace_context propagate;
            proxy_pass http://web-service:8000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /auth/ {
            otel_trace_context propagate;
            proxy_pass http://auth-service:8000/;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /v1/ {
            otel_trace_context propagate;
            proxy_pass http://api-service:8000/;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
